sudo: required

services:
  - docker

install:
  - cp config/database.yml.example config/database.yml
  - cp config/config.yml.example config/config.yml
  - docker-compose build
  - docker-compose run web bower install --allow-root
  - docker-compose run web rake assets:precompile --trace
  - docker-compose run web rake db:setup

script:
  - docker-compose run web rake test_all
